name: CI/CD Pipeline Java

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 4. Login no DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Debug seguro (opcional)
      #- name: Debug DockerHub Secrets
      #  run: echo "Token configurado com sucesso. Tamanho: $(echo -n ${{ secrets.DOCKERHUB_TOKEN }} | wc -c) caracteres"

      # 6. Build e push da imagem para o DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: romaofr/meu-projeto-java:1.0
